---
output: pdf_document
---

Dear Editor,

We are pleased to submit this paper to [TODO].

The paper, titled "Check your outliers! An accessible introduction to identifying statistical outliers in R with *easystats*", provides an overview of current recommendations and best practices regarding the diagnosis and treatment of outliers, a common issue faced by researchers - and a potential source of scientific malpractice. 

It explains the key approaches and highlights recommendations, and shows how users can adopt them in their R analysis with just one function. The manuscript covers univariate, multivariate, and model-based statistical outlier detection methods, their recommended threshold, standard output, and plotting method, among other things.

Beyond acting like a concise review of outlier treatment procedures and practical tutorial, we also describe a new method (a consensus-based approach) and discuss its benefits ad limitations. In this sense, the paper fits very well with the scope of the journal, as it essentially communicates to the wider public current advances in the statistical computing of outlier detection algorithms and their implementation in currently available open source and free software. This makes the manuscript relevant to data science, behavioural science, and statistical computing more generally. 
<!-- Adapt the previous to new journal -->

Our current submission is original and has been neither published elsewhere nor is currently under consideration for publication elsewhere. All authors have contributed substantially to the software and manuscript. All authors gave final approval to the manuscript and accept to be accountable. We have no conflicts of interest to disclose.

<!-- We would also like to use the open peer review option. -->

Thank you for considering our submission.

On the behalf of all authors,

Rémi Thériault

Department of Psychology,

Université du Québec à Montréal,

Montréal, Québec, Canada