---
title: "Assessing Model Variance: R-Squared and Intraclass Correlation Coefficient"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Assessing Model Variance}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: bibliography.bib
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, 
  comment = "#>", 
  message = FALSE, 
  warning = FALSE,
  width = 800
)
```

```{r setup}
library(performance)
```

## R-Squared

### R-Squared for Mixed Models

[@nakagawa_coefficient_2017] proposed a method to compute marginal and conditional r-squared values, which is implemented in the `r2_nakagawa()`-function. For mixed models, the marginal r-squared considers only the variance of the fixed effects, while the conditional r-squared takes both the fixed and random effects into account. The random effect variances are actually the mean random effect variances, thus the r-squared value is also appropriate for mixed models with random slopes or nested random effects (see [@johnson_extension_2014]).

# References
