---
output: pdf_document
---

Dear Editors,

We are pleased to submit this paper to *Mathematics*, for the special issue "Advances in Statistical Computing".

The paper, titled "Check your outliers! An accessible introduction to identifying statistical outliers in R with *easystats*", provides an overview of current recommendations and best practices regarding the diagnosis and treament of outliers. It demonstrates how these recommendations can be easily and conveniently implemented in the R software using the *{performance}* package of the *easystats* ecosystem. The manuscript covers univariate, multivariate, and model-based statistical outlier detection methods, their recommended threshold, standard output, and plotting method, among other things.

In this sense, the paper fits very well with the special issue "Advances in Statistical Computing", as it essentially communicates to the wider public current advances in the statistical computing of outlier detection algorithms and their implementation in currently available open source and free software. This makes the manuscript relevant to data science, behavioural science, and statistical computing more generally.

Our current submission is original and has been neither published elsewhere nor is currently under consideration for publication elsewhere. All authors have contributed substantially to the software and manuscript. All authors gave final approval to the manuscript and accept to be accountable. We have no conflicts of interest to disclose.

We would also like to use the open peer review option.

Thank you for considering our submission.

Best Regards,

Rémi Thériault

Department of Psychology,

Université du Québec à Montréal,

Montréal, Québec, Canada